-- Add table comment
ALTER TABLE brset COMMENT = 'BRSET (Brazilian Multilabel Ophthalmological Dataset) containing retinal fundus images with comprehensive patient demographics and clinical characteristics for multi-label ophthalmological classification tasks.';

-- Add column comments
ALTER TABLE brset
    MODIFY COLUMN image_id varchar(255) COMMENT 'Unique identifier for each fundus image',
    MODIFY COLUMN patient_id int COMMENT 'Unique identifier for each patient',
    MODIFY COLUMN camera varchar(255) COMMENT 'Retinal camera used: Nikon NF505 or Canon CR-2',
    MODIFY COLUMN patient_age float COMMENT 'Patient age in years (range: 5-97, average: 57.84)',
    MODIFY COLUMN comorbidities varchar(255) COMMENT 'Patient comorbidities information',
    MODIFY COLUMN diabetes_time_y varchar(255) COMMENT 'Duration of diabetes in years',
    MODIFY COLUMN insuline varchar(255) COMMENT 'Insulin usage status',
    MODIFY COLUMN patient_sex int COMMENT 'Patient gender: 1=male, 2=female',
    MODIFY COLUMN exam_eye int COMMENT 'Examined eye: 1=right, 2=left',
    MODIFY COLUMN diabetes varchar(255) COMMENT 'Diabetes status',
    MODIFY COLUMN nationality varchar(255) COMMENT 'Patient nationality',
    MODIFY COLUMN optic_disc varchar(255) COMMENT 'Optic disc classification: normal/abnormal',
    MODIFY COLUMN vessels int COMMENT 'Retinal vessels classification: 1=normal, 2=abnormal',
    MODIFY COLUMN macula int COMMENT 'Macula classification: 1=normal, 2=abnormal',
    MODIFY COLUMN DR_SDRG int COMMENT 'Scottish Diabetic Retinopathy Grading: 0-4',
    MODIFY COLUMN DR_ICDR int COMMENT 'International Clinic Diabetic Retinopathy classification: 0-4',
    MODIFY COLUMN focus int COMMENT 'Image focus quality: 1=satisfactory, 2=unsatisfactory',
    MODIFY COLUMN Illuminaton int COMMENT 'Image illumination quality: 1=satisfactory, 2=unsatisfactory',
    MODIFY COLUMN image_field int COMMENT 'Image field adequacy: 1=satisfactory, 2=unsatisfactory',
    MODIFY COLUMN artifacts int COMMENT 'Artifacts presence: 1=satisfactory, 2=unsatisfactory',
    MODIFY COLUMN diabetic_retinopathy int COMMENT 'Diabetic retinopathy presence: 1=present, 0=absent',
    MODIFY COLUMN macular_edema int COMMENT 'Diabetic macular edema presence: 1=present, 0=absent',
    MODIFY COLUMN scar int COMMENT 'Scar (toxoplasmosis) presence: 1=present, 0=absent',
    MODIFY COLUMN nevus int COMMENT 'Nevus presence: 1=present, 0=absent',
    MODIFY COLUMN amd int COMMENT 'Age-related macular degeneration presence: 1=present, 0=absent',
    MODIFY COLUMN vascular_occlusion int COMMENT 'Vascular occlusion presence: 1=present, 0=absent',
    MODIFY COLUMN hypertensive_retinopathy int COMMENT 'Hypertensive retinopathy presence: 1=present, 0=absent',
    MODIFY COLUMN drusens int COMMENT 'Drusens presence: 1=present, 0=absent',
    MODIFY COLUMN hemorrhage int COMMENT 'Non-diabetic retinal hemorrhage presence: 1=present, 0=absent',
    MODIFY COLUMN retinal_detachment int COMMENT 'Retinal detachment presence: 1=present, 0=absent',
    MODIFY COLUMN myopic_fundus int COMMENT 'Myopic fundus presence: 1=present, 0=absent',
    MODIFY COLUMN increased_cup_disc int COMMENT 'Increased cup-disc ratio presence: 1=present, 0=absent',
    MODIFY COLUMN other int COMMENT 'Other pathologies presence: 1=present, 0=absent',
    MODIFY COLUMN quality varchar(255) COMMENT 'Overall image quality assessment';